hwk1/blueprints/courses_blueprint.py
    
from flask import Blueprint, request, render_template
from flask import jsonify

course_list = [
    {"id": 1, "name": "BUS"},
    {"id": 2, "name": "INF"},
    {"id": 3, "name": "ECO"}
]

course_bluep = Blueprint('course_bluep', __name__, template_folder='templates')
    

@course_bluep.route("/<int:course_id>/<name>", methods=['POST', 'PUT'])               
def course_put_post(course_id,name):
    if request.method == 'POST':
        id_exist = False
        for i in range(len(course_list)):
            if course_list[i-1]['id'] == course_id:
                id_exist = True
    
        if id_exist == False:
            course_list.append(dict({'id': course_id, 'name': name}))
            return jsonify(course_list)
        else:
            return "ID already exist"

    else:
        for a in course_list:
            if a["id"] == course_id:
                a.update({'name': name})
                return jsonify(a)

        course_list.append(dict({'id': course_id, 'name': name}))
        return jsonify(course_list)
    

@course_bluep.route("/<int:course_id>", methods=['GET', 'DELETE'])                              
def course_delete_get(course_id):
    if request.method == 'GET':
        flag = False
        for course in course_list:
            if course["id"] == course_id:
                flag = True
                return jsonify(course)
        if flag == False:    
            return "ID not Found!"


    else:
        flag = False
        for i in range(len(course_list)): 
            if course_list[i]['id'] == course_id: 
                del course_list[i]
                flag = True
                return "Course deleted!"

        if flag == False:
            return "ID not Found!"




@course_bluep.route("/all", methods=['GET'])
def get_all():
    return render_template('course.html', courses=course_list)

hwk1/blueprints/event_blueprint.py
from flask import Blueprint, request, render_template
from flask import jsonify

event_list = [
    {"id": 1, "event": "rock concert"},
    {"id": 2, "event": "free banichki"},
    {"id": 3, "event": "coffe time"}
]

event_bluep = Blueprint('event_bluep', __name__, template_folder='templates')

    

@event_bluep.route("/<int:event_id>/<event>", methods=['POST', 'PUT'])                              
def event_put_post(event_id, event):
    if request.method == 'POST':
        id_exist = False
        for i in range(len(event_list)):
            if event_list[i-1]['id'] == event_id:
                id_exist = True
        
        if id_exist == False:
            event_list.append(dict({'id': event_id, 'event': event}))
            return jsonify(event_list)
        else:
            return "ID already exist"

    else:
        for a in event_list:
            if a["id"] == event_id:
                a.update({'event': event})
                return jsonify(a)

        event_list.append(dict({'id': event_id, 'event': event}))
        return jsonify(event_list)

    
    

@event_bluep.route("/<int:event_id>", methods=['GET', 'DELETE'])
def event_delete_get(event_id):
    if request.method == 'GET':
        flag = False
        for event in event_list:
            if event["id"] == event_id:
                flag = True
                return jsonify(event)
        if flag == False:    
            return "ID not Found!"


    else:
        flag = False
        for i in range(len(event_list)): 
            if event_list[i]['id'] == event_id: 
                del event_list[i] 
                flag = True
                return "Event deleted!"

        if flag == False:
            return "ID not Found!"
    

@event_bluep.route("/all", methods=['GET'])
def get_all():
    return render_template('event.html', events=event_list)

hwk1/templates/courses.html
{% extends "home.html" %}
{% block body %}

        <table>
                <tbody>
                        {% for course in courses %}
                            {% for key, value in course.items() %}
                            <h4>Key: {{key}}</h4>
                            <h4>Value: {{value}}</h4>
                            {% endfor %}
                        {% endfor %}
                </tbody>
        </table>

{% endblock %} 

hwk1/templates/event.html
{% extends "home.html" %}
{% block body %}

        <table>
                <tbody>
                        {% for event in events %}
                            {% for key, value in event.items() %}
                            <h4>Key: {{key}}</h4>
                            <h4>Value: {{value}}</h4>
                            {% endfor %}
                        {% endfor %}
                </tbody>
        </table>

{% endblock %}

hwk1/templates/home.html
<!DOCTYPE html>
<html>
<body>

        <a href="{{url_for('course_bluep.get_all')}}">List of all courses</a> 
        <a href="{{url_for('student_bluep.get_all')}}">List of all students</a> 
        <a href="{{url_for('event_bluep.get_all')}}">List of all events</a> 

        {% block body %}{% endblock %}


</body>
</html

hwk1/templates/student.html
{% extends "home.html" %}
{% block body %}

        <table>
                <tbody>
                        {% for student in students %}
                            {% for key, value in student.items() %}
                            <h4>Key: {{key}}</h4>
                            <h4>Value: {{value}}</h4>
                            {% endfor %}
                        {% endfor %}
                </tbody>
        </table>
{% endblock %}